language: perl
env:
  - IN_TRAVIS=1 AUTHOR_TESTING=1
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.18"
  - "5.16"
sudo: false
cache:
  directories:
    - $HOME/.carton
before_install:
  - cpanm Carton
install:
  - carton install --path $HOME/.carton
script:
  - export PERL_CARTON_PATH=$HOME/.carton
  - carton exec cover -delete
  - carton exec perl -MDevel::Cover=+ignore,^local/,^t/ t/compile.t
  - carton exec perl -MDevel::Cover=+ignore,^local/,^t/ t/plugins.t
  - carton exec perl build-bin/dzil-plugins.pl -c build
  - carton exec perl build-bin/dzil-plugins.pl -c test
after_success:
  - cover -report codecov

