language: perl
env:
  - IN_TRAVIS=1 AUTHOR_TESTING=1
perl:
  - "5.24"
  - "5.22"
  - "5.18"
  - "5.16"
sudo: false
before_install:
  - cpanm Carton
install:
  - carton install
script:
  - carton exec build-bin/dzil-plugins.pl test
